# Self-contained Ansible playbook for setting up the Embassy IDR NFS shares
- hosts: >
    {{ idr_environment | default('idr') }}-uod-nfs
    {{ idr_environment | default('idr') }}-a-uod-nfs
    {{ idr_environment | default('idr') }}-ebi-nfs
    {{ idr_environment | default('idr') }}-a-ebi-nfs

  tasks:

  - name: Create NFS group
    become: yes
    group:
      gid: "{{ idr_nfs.groupid | default(omit) }}"
      name: "{{ idr_nfs.groupname }}"
      state: present
    when: 'idr_nfs.groupname is defined'

  - name: Create NFS user
    become: yes
    user:
      group: "{{ idr_nfs.groupname | default(omit) }}"
      name: "{{ idr_nfs.username }}"
      state: present
      uid: "{{ idr_nfs.userid | default(omit) }}"
    when: 'idr_nfs.username is defined'

  - name: Mount NFS share
    become: yes
    mount:
      fstype: nfs
      name: "{{ idr_nfs.mountpoint }}"
      # Removed rsize=8192,wsize=8192, this should be auto-negotiated
      opts: "{{ idr_nfs.mountopts | default(omit) }}"
      src: "{{ idr_nfs.server }}"
      state: mounted

  - name: Create filesets parent dir
    become: yes
    file:
      path: "{{ local_filesets_sym | dirname }}"
      state: directory

  # This is needed to prevent the next file task returning an error
  - name: Check for existing filesets object
    stat:
      path: "{{ local_filesets_sym }}"
    register: local_filesets_sym_st

  - name: Create filesets symlink
    become: yes
    file:
      path: "{{ local_filesets_sym }}"
      src: "{{ nfs_filesets_dir }}"
      state: link
    when: "{{ not local_filesets_sym_st.stat.exists }}"


  vars:
    idr_nfs:
      groupid: 1030
      groupname: idrnfs
      userid: 6166
      username: idrnfs
      server: 10.35.106.250:/ivol_bioimage_sm
      mountpoint: /nfs/bioimage
      mountopts: timeo=14,intr,nolock
    nfs_filesets_dir: /nfs/bioimage/drop/complete
    local_filesets_sym: /uod/idr/filesets
